name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNDk0M2M5ZjQtN2NlNS00N2MyLWE0YTQtYTM5YTQxNDI1NTQ4IiwidGVuYW50X2lkIjoiY2VhYzVjZGFkZjZjNzY5ZjBhMTAyNGYwZTM3Mjk0NDgwMTM3YTk4NmE2YjUzOThiNmQwNDI3ZDlmMzFjNjNjYyIsImludGVybmFsX3NlY3JldCI6IjUyZTVlNzIxLWU5MmEtNGQ1NS05Zjk3LWJkYWZiNDFhZWY5MCJ9.EvmSffll0thp4hJYX8nc4Jgac8IIRdD7m3S99ygf8Q0"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"